# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alexander Grebenyuk
email: grebenyuk.alexander@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Programming in Swift, Objective-C.
twitter_username: a_grebenyuk
github_username: kean

# Build settings
markdown: kramdown
future: true
lsi: true

# Site specific
# e.g. f7b08862-3571-4c61-a7a2-9a5f742fc10a
featured_posts:
  - 0b507d56-2cd1-402f-be3e-f1f39645e3d3

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      social:
        name: "Alexander Grebenyuk"
        links:
          - https://twitter.com/a_grebenyuk
          - https://www.linkedin.com/in/alexander-grebenyuk
          - https://github.com/kean
          - https://www.flickr.com/photos/agrebenyuk/
